kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myclaim
  annotations:
    iscsi-provisioner/thin: "true"
spec:
  storageClassName: iscsi-target-api-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 17Mi
