kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: iscsi-target-api-sc
provisioner: iscsi-target-api
parameters:
  # REQUIRED: this id where the iscsi server is running
  targetPortal: 192.168.1.111:3260
  # REQUIRED: MUST follow iscsi-target-api configuration
  volumeGroup: "vg-0"
  volumeType: "lvm"
  # OPTIONAL: thinPool is required if thinProvision is true, and volumeType is LVM
  thinPool: "pool0"
  # OPTIONAL: Whether the volume should be mounted in readonly mode, default false
  readonly: "false"
  # OPTIONAL: This is the filesystem you want your volume to be formatted with, default value depends on provisioner
  #           default-fs parameter
  fsType: "xfs"
  # OPTIONAL: This is a comma separated list of IP or CIDR of initiators. default is ALL
#  acl: "192.168.1.0/24"
  # OPTIONAL: if you are using multipath, you can specify additional IPs here, default empty
  # portals: "192.168.99.101:3260,192.168.99.102:3260"

